# pre build
FROM riskiwah/tdewolff-minify:latest as pre

FROM golang:1.23.3-alpine3.20 as builder
RUN apk --no-cache add git make
COPY --from=pre /usr/bin/minify /usr/bin/minify
WORKDIR /nothingtodo
RUN mkdir -p /nothingtodo/data && chown 65534:65534 /nothingtodo/data
ADD . /nothingtodo
RUN go mod download \
    && make minify \
    && make build

# runtime
FROM scratch as runtime
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /nothingtodo/dist/nothingtodo .
COPY --from=builder --chown=65534:65534 /nothingtodo/data /data
USER 65534:65534
VOLUME ["/data"]
ENTRYPOINT ["./nothingtodo"]
